# Generated by Django 5.2.1 on 2025-05-28 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('country', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('office_designation', models.CharField(max_length=100)),
                ('office_name', models.CharField(max_length=100)),
                ('visiting_purpose', models.CharField(max_length=200)),
                ('visit_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
