# Generated by Django 5.2.1 on 2025-05-30 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='mobile',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='visitor',
            name='organization',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='visitor',
            name='visit_out_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
