# Generated by Django 5.2.1 on 2025-05-30 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_visitor_mobile_visitor_organization_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='visitor_photos/'),
        ),
    ]
