# Generated by Django 5.2.1 on 2025-05-30 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_visitor_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='punch_out_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visitor',
            name='rites_officer',
            field=models.CharField(default='2', max_length=100),
        ),
    ]
