# Generated by Django 5.2.1 on 2025-05-30 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_visitor_punch_out_time_visitor_rites_officer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitor',
            name='rites_officer',
        ),
    ]
